// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/idp/entities.proto

package com.tcn.cloud.api.api.v1alpha1.idp;

public interface GetAuthConnectionRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1alpha1.idp.GetAuthConnectionRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The id of the connetion to retrieve.
   * </pre>
   *
   * <code>string connection_id = 1 [json_name = "connectionId"];</code>
   * @return The connectionId.
   */
  java.lang.String getConnectionId();
  /**
   * <pre>
   * The id of the connetion to retrieve.
   * </pre>
   *
   * <code>string connection_id = 1 [json_name = "connectionId"];</code>
   * @return The bytes for connectionId.
   */
  com.google.protobuf.ByteString
      getConnectionIdBytes();
}
