// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/commons/integrations/integrations.proto

package com.tcn.cloud.api.api.commons.integrations;

public interface ExecuteBraintreeBankSaleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.commons.integrations.ExecuteBraintreeBankSale)
    com.google.protobuf.MessageOrBuilder {
}
