// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/agenttraining/learning_opportunity.proto

package com.tcn.cloud.api.api.v1alpha1.agenttraining;

public final class LearningOpportunityProto {
  private LearningOpportunityProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n5api/v1alpha1/agenttraining/learning_op" +
      "portunity.proto\022\032api.v1alpha1.agenttrain" +
      "ing\032 api/commons/agent_training.proto\032 g" +
      "oogle/protobuf/field_mask.proto\"w\n Creat" +
      "eLearningOpportunityRequest\022S\n\024learning_" +
      "opportunity\030\001 \001(\0132 .api.commons.Learning" +
      "OpportunityR\023learningOpportunity\"x\n!Crea" +
      "teLearningOpportunityResponse\022S\n\024learnin" +
      "g_opportunity\030\001 \001(\0132 .api.commons.Learni" +
      "ngOpportunityR\023learningOpportunity\"\"\n Li" +
      "stLearningOpportunitiesRequest\"|\n!ListLe" +
      "arningOpportunitiesResponse\022W\n\026learning_" +
      "opportunities\030\001 \003(\0132 .api.commons.Learni" +
      "ngOpportunityR\025learningOpportunities\"\'\n%" +
      "ListAgentLearningOpportunitiesRequest\"\201\001" +
      "\n&ListAgentLearningOpportunitiesResponse" +
      "\022W\n\026learning_opportunities\030\001 \003(\0132 .api.c" +
      "ommons.LearningOpportunityR\025learningOppo" +
      "rtunities\"\264\001\n UpdateLearningOpportunityR" +
      "equest\022S\n\024learning_opportunity\030\002 \001(\0132 .a" +
      "pi.commons.LearningOpportunityR\023learning" +
      "Opportunity\022;\n\013update_mask\030\003 \001(\0132\032.googl" +
      "e.protobuf.FieldMaskR\nupdateMask\"x\n!Upda" +
      "teLearningOpportunityResponse\022S\n\024learnin" +
      "g_opportunity\030\001 \001(\0132 .api.commons.Learni" +
      "ngOpportunityR\023learningOpportunity\"Z\n De" +
      "leteLearningOpportunityRequest\0226\n\027learni" +
      "ng_opportunity_id\030\003 \001(\003R\025learningOpportu" +
      "nityId\"x\n!DeleteLearningOpportunityRespo" +
      "nse\022S\n\024learning_opportunity\030\001 \001(\0132 .api." +
      "commons.LearningOpportunityR\023learningOpp" +
      "ortunity\"R\n\035GetLearningOpportunityReques" +
      "t\0221\n\024learning_opportunity\030\002 \001(\003R\023learnin" +
      "gOpportunity\"u\n\036GetLearningOpportunityRe" +
      "sponse\022S\n\024learning_opportunity\030\001 \001(\0132 .a" +
      "pi.commons.LearningOpportunityR\023learning" +
      "OpportunityB\322\001\n,com.tcn.cloud.api.api.v1" +
      "alpha1.agenttrainingB\030LearningOpportunit" +
      "yProtoP\001\242\002\003AVA\252\002\032Api.V1alpha1.Agenttrain" +
      "ing\312\002\032Api\\V1alpha1\\Agenttraining\342\002&Api\\V" +
      "1alpha1\\Agenttraining\\GPBMetadata\352\002\034Api:" +
      ":V1alpha1::Agenttrainingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.tcn.cloud.api.api.commons.AgentTrainingProto.getDescriptor(),
          com.google.protobuf.FieldMaskProto.getDescriptor(),
        });
    internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityRequest_descriptor,
        new java.lang.String[] { "LearningOpportunity", });
    internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_CreateLearningOpportunityResponse_descriptor,
        new java.lang.String[] { "LearningOpportunity", });
    internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_ListLearningOpportunitiesResponse_descriptor,
        new java.lang.String[] { "LearningOpportunities", });
    internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesRequest_descriptor,
        new java.lang.String[] { });
    internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_ListAgentLearningOpportunitiesResponse_descriptor,
        new java.lang.String[] { "LearningOpportunities", });
    internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityRequest_descriptor,
        new java.lang.String[] { "LearningOpportunity", "UpdateMask", });
    internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_UpdateLearningOpportunityResponse_descriptor,
        new java.lang.String[] { "LearningOpportunity", });
    internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityRequest_descriptor,
        new java.lang.String[] { "LearningOpportunityId", });
    internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_DeleteLearningOpportunityResponse_descriptor,
        new java.lang.String[] { "LearningOpportunity", });
    internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityRequest_descriptor =
      getDescriptor().getMessageTypes().get(10);
    internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityRequest_descriptor,
        new java.lang.String[] { "LearningOpportunity", });
    internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityResponse_descriptor =
      getDescriptor().getMessageTypes().get(11);
    internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_api_v1alpha1_agenttraining_GetLearningOpportunityResponse_descriptor,
        new java.lang.String[] { "LearningOpportunity", });
    com.tcn.cloud.api.api.commons.AgentTrainingProto.getDescriptor();
    com.google.protobuf.FieldMaskProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
