// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/insights/insight.proto

package com.tcn.cloud.api.api.v1alpha1.insights;

public interface DeriveNodeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1alpha1.insights.DeriveNode)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string column_name = 3 [json_name = "columnName"];</code>
   * @return The columnName.
   */
  java.lang.String getColumnName();
  /**
   * <code>string column_name = 3 [json_name = "columnName"];</code>
   * @return The bytes for columnName.
   */
  com.google.protobuf.ByteString
      getColumnNameBytes();

  /**
   * <code>.api.v1alpha1.insights.ExpressionNode expression = 4 [json_name = "expression"];</code>
   * @return Whether the expression field is set.
   */
  boolean hasExpression();
  /**
   * <code>.api.v1alpha1.insights.ExpressionNode expression = 4 [json_name = "expression"];</code>
   * @return The expression.
   */
  com.tcn.cloud.api.api.v1alpha1.insights.ExpressionNode getExpression();
  /**
   * <code>.api.v1alpha1.insights.ExpressionNode expression = 4 [json_name = "expression"];</code>
   */
  com.tcn.cloud.api.api.v1alpha1.insights.ExpressionNodeOrBuilder getExpressionOrBuilder();
}
