// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/pbx/v2/service.proto

package com.tcn.cloud.api.services.pbx.v2;

public interface GetSipCredentialsRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.pbx.v2.GetSipCredentialsRequest)
    com.google.protobuf.MessageOrBuilder {
}
