// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/room303/room.proto

package com.tcn.cloud.api.api.v1alpha1.room303;

public interface UpdateGlobalConfigResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1alpha1.room303.UpdateGlobalConfigResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * last edited_by user
   * </pre>
   *
   * <code>string edited_by = 1 [json_name = "editedBy"];</code>
   * @return The editedBy.
   */
  java.lang.String getEditedBy();
  /**
   * <pre>
   * last edited_by user
   * </pre>
   *
   * <code>string edited_by = 1 [json_name = "editedBy"];</code>
   * @return The bytes for editedBy.
   */
  com.google.protobuf.ByteString
      getEditedByBytes();

  /**
   * <pre>
   * global configuration details
   * </pre>
   *
   * <code>.api.commons.GlobalConfig config = 2 [json_name = "config"];</code>
   * @return Whether the config field is set.
   */
  boolean hasConfig();
  /**
   * <pre>
   * global configuration details
   * </pre>
   *
   * <code>.api.commons.GlobalConfig config = 2 [json_name = "config"];</code>
   * @return The config.
   */
  com.tcn.cloud.api.api.commons.GlobalConfig getConfig();
  /**
   * <pre>
   * global configuration details
   * </pre>
   *
   * <code>.api.commons.GlobalConfig config = 2 [json_name = "config"];</code>
   */
  com.tcn.cloud.api.api.commons.GlobalConfigOrBuilder getConfigOrBuilder();

  /**
   * <pre>
   * date created
   * </pre>
   *
   * <code>.google.protobuf.Timestamp date_created = 3 [json_name = "dateCreated"];</code>
   * @return Whether the dateCreated field is set.
   */
  boolean hasDateCreated();
  /**
   * <pre>
   * date created
   * </pre>
   *
   * <code>.google.protobuf.Timestamp date_created = 3 [json_name = "dateCreated"];</code>
   * @return The dateCreated.
   */
  com.google.protobuf.Timestamp getDateCreated();
  /**
   * <pre>
   * date created
   * </pre>
   *
   * <code>.google.protobuf.Timestamp date_created = 3 [json_name = "dateCreated"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDateCreatedOrBuilder();

  /**
   * <pre>
   * last edited on
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_edited = 4 [json_name = "lastEdited"];</code>
   * @return Whether the lastEdited field is set.
   */
  boolean hasLastEdited();
  /**
   * <pre>
   * last edited on
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_edited = 4 [json_name = "lastEdited"];</code>
   * @return The lastEdited.
   */
  com.google.protobuf.Timestamp getLastEdited();
  /**
   * <pre>
   * last edited on
   * </pre>
   *
   * <code>.google.protobuf.Timestamp last_edited = 4 [json_name = "lastEdited"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getLastEditedOrBuilder();
}
