// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/org/user.proto

package com.tcn.cloud.api.api.v1alpha1.org;

public interface UpdateUserRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1alpha1.org.UpdateUserRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * The user id of the user to be updated
   * </pre>
   *
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The userId.
   */
  java.lang.String getUserId();
  /**
   * <pre>
   * The user id of the user to be updated
   * </pre>
   *
   * <code>string user_id = 1 [json_name = "userId"];</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <pre>
   * The first name the updated user will have.
   * </pre>
   *
   * <code>string first_name = 2 [json_name = "firstName"];</code>
   * @return The firstName.
   */
  java.lang.String getFirstName();
  /**
   * <pre>
   * The first name the updated user will have.
   * </pre>
   *
   * <code>string first_name = 2 [json_name = "firstName"];</code>
   * @return The bytes for firstName.
   */
  com.google.protobuf.ByteString
      getFirstNameBytes();

  /**
   * <pre>
   * The last name the updated user will have.
   * </pre>
   *
   * <code>string last_name = 3 [json_name = "lastName"];</code>
   * @return The lastName.
   */
  java.lang.String getLastName();
  /**
   * <pre>
   * The last name the updated user will have.
   * </pre>
   *
   * <code>string last_name = 3 [json_name = "lastName"];</code>
   * @return The bytes for lastName.
   */
  com.google.protobuf.ByteString
      getLastNameBytes();

  /**
   * <pre>
   * The partner agent id the updated user will have.
   * </pre>
   *
   * <code>string partner_agent_id = 4 [json_name = "partnerAgentId"];</code>
   * @return The partnerAgentId.
   */
  java.lang.String getPartnerAgentId();
  /**
   * <pre>
   * The partner agent id the updated user will have.
   * </pre>
   *
   * <code>string partner_agent_id = 4 [json_name = "partnerAgentId"];</code>
   * @return The bytes for partnerAgentId.
   */
  com.google.protobuf.ByteString
      getPartnerAgentIdBytes();

  /**
   * <pre>
   * User TimeZone with wrapper for nullable timezone.
   * </pre>
   *
   * <code>.api.commons.TimeZoneWrapper time_zone_override = 5 [json_name = "timeZoneOverride"];</code>
   * @return Whether the timeZoneOverride field is set.
   */
  boolean hasTimeZoneOverride();
  /**
   * <pre>
   * User TimeZone with wrapper for nullable timezone.
   * </pre>
   *
   * <code>.api.commons.TimeZoneWrapper time_zone_override = 5 [json_name = "timeZoneOverride"];</code>
   * @return The timeZoneOverride.
   */
  com.tcn.cloud.api.api.commons.TimeZoneWrapper getTimeZoneOverride();
  /**
   * <pre>
   * User TimeZone with wrapper for nullable timezone.
   * </pre>
   *
   * <code>.api.commons.TimeZoneWrapper time_zone_override = 5 [json_name = "timeZoneOverride"];</code>
   */
  com.tcn.cloud.api.api.commons.TimeZoneWrapperOrBuilder getTimeZoneOverrideOrBuilder();

  /**
   * <pre>
   * The linkback numbers the updated user will have.
   * </pre>
   *
   * <code>repeated string linkback_numbers = 6 [json_name = "linkbackNumbers"];</code>
   * @return A list containing the linkbackNumbers.
   */
  java.util.List<java.lang.String>
      getLinkbackNumbersList();
  /**
   * <pre>
   * The linkback numbers the updated user will have.
   * </pre>
   *
   * <code>repeated string linkback_numbers = 6 [json_name = "linkbackNumbers"];</code>
   * @return The count of linkbackNumbers.
   */
  int getLinkbackNumbersCount();
  /**
   * <pre>
   * The linkback numbers the updated user will have.
   * </pre>
   *
   * <code>repeated string linkback_numbers = 6 [json_name = "linkbackNumbers"];</code>
   * @param index The index of the element to return.
   * @return The linkbackNumbers at the given index.
   */
  java.lang.String getLinkbackNumbers(int index);
  /**
   * <pre>
   * The linkback numbers the updated user will have.
   * </pre>
   *
   * <code>repeated string linkback_numbers = 6 [json_name = "linkbackNumbers"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the linkbackNumbers at the given index.
   */
  com.google.protobuf.ByteString
      getLinkbackNumbersBytes(int index);

  /**
   * <pre>
   * The caller ids the updated user will have.
   * </pre>
   *
   * <code>repeated string caller_ids = 7 [json_name = "callerIds"];</code>
   * @return A list containing the callerIds.
   */
  java.util.List<java.lang.String>
      getCallerIdsList();
  /**
   * <pre>
   * The caller ids the updated user will have.
   * </pre>
   *
   * <code>repeated string caller_ids = 7 [json_name = "callerIds"];</code>
   * @return The count of callerIds.
   */
  int getCallerIdsCount();
  /**
   * <pre>
   * The caller ids the updated user will have.
   * </pre>
   *
   * <code>repeated string caller_ids = 7 [json_name = "callerIds"];</code>
   * @param index The index of the element to return.
   * @return The callerIds at the given index.
   */
  java.lang.String getCallerIds(int index);
  /**
   * <pre>
   * The caller ids the updated user will have.
   * </pre>
   *
   * <code>repeated string caller_ids = 7 [json_name = "callerIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the callerIds at the given index.
   */
  com.google.protobuf.ByteString
      getCallerIdsBytes(int index);

  /**
   * <pre>
   * Default app the user starts on
   * </pre>
   *
   * <code>.api.commons.OperatorApplications default_app = 8 [json_name = "defaultApp"];</code>
   * @return The enum numeric value on the wire for defaultApp.
   */
  int getDefaultAppValue();
  /**
   * <pre>
   * Default app the user starts on
   * </pre>
   *
   * <code>.api.commons.OperatorApplications default_app = 8 [json_name = "defaultApp"];</code>
   * @return The defaultApp.
   */
  com.tcn.cloud.api.api.commons.OperatorApplications getDefaultApp();

  /**
   * <pre>
   * Whether the updated user will require a password reset.
   * </pre>
   *
   * <code>bool password_reset_required = 9 [json_name = "passwordResetRequired"];</code>
   * @return The passwordResetRequired.
   */
  boolean getPasswordResetRequired();

  /**
   * <pre>
   * The agent profile group id the updated user will have.
   * </pre>
   *
   * <code>string agent_profile_group_id = 10 [json_name = "agentProfileGroupId"];</code>
   * @return The agentProfileGroupId.
   */
  java.lang.String getAgentProfileGroupId();
  /**
   * <pre>
   * The agent profile group id the updated user will have.
   * </pre>
   *
   * <code>string agent_profile_group_id = 10 [json_name = "agentProfileGroupId"];</code>
   * @return The bytes for agentProfileGroupId.
   */
  com.google.protobuf.ByteString
      getAgentProfileGroupIdBytes();

  /**
   * <pre>
   * The username the updated user will have.
   * </pre>
   *
   * <code>string username = 11 [json_name = "username"];</code>
   * @return The username.
   */
  java.lang.String getUsername();
  /**
   * <pre>
   * The username the updated user will have.
   * </pre>
   *
   * <code>string username = 11 [json_name = "username"];</code>
   * @return The bytes for username.
   */
  com.google.protobuf.ByteString
      getUsernameBytes();

  /**
   * <pre>
   * The email the updated user will have.
   * </pre>
   *
   * <code>string email = 12 [json_name = "email"];</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <pre>
   * The email the updated user will have.
   * </pre>
   *
   * <code>string email = 12 [json_name = "email"];</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <pre>
   * The Agent Caller Id of the user
   * </pre>
   *
   * <code>string user_caller_id = 13 [json_name = "userCallerId"];</code>
   * @return The userCallerId.
   */
  java.lang.String getUserCallerId();
  /**
   * <pre>
   * The Agent Caller Id of the user
   * </pre>
   *
   * <code>string user_caller_id = 13 [json_name = "userCallerId"];</code>
   * @return The bytes for userCallerId.
   */
  com.google.protobuf.ByteString
      getUserCallerIdBytes();

  /**
   * <pre>
   * A list of labels to assign to the user
   * </pre>
   *
   * <code>repeated string label_ids = 14 [json_name = "labelIds"];</code>
   * @return A list containing the labelIds.
   */
  java.util.List<java.lang.String>
      getLabelIdsList();
  /**
   * <pre>
   * A list of labels to assign to the user
   * </pre>
   *
   * <code>repeated string label_ids = 14 [json_name = "labelIds"];</code>
   * @return The count of labelIds.
   */
  int getLabelIdsCount();
  /**
   * <pre>
   * A list of labels to assign to the user
   * </pre>
   *
   * <code>repeated string label_ids = 14 [json_name = "labelIds"];</code>
   * @param index The index of the element to return.
   * @return The labelIds at the given index.
   */
  java.lang.String getLabelIds(int index);
  /**
   * <pre>
   * A list of labels to assign to the user
   * </pre>
   *
   * <code>repeated string label_ids = 14 [json_name = "labelIds"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the labelIds at the given index.
   */
  com.google.protobuf.ByteString
      getLabelIdsBytes(int index);

  /**
   * <pre>
   * The override for the users locale preferences
   * </pre>
   *
   * <code>.api.commons.LocalePreferences locale_preferences_override = 15 [json_name = "localePreferencesOverride"];</code>
   * @return Whether the localePreferencesOverride field is set.
   */
  boolean hasLocalePreferencesOverride();
  /**
   * <pre>
   * The override for the users locale preferences
   * </pre>
   *
   * <code>.api.commons.LocalePreferences locale_preferences_override = 15 [json_name = "localePreferencesOverride"];</code>
   * @return The localePreferencesOverride.
   */
  com.tcn.cloud.api.api.commons.LocalePreferences getLocalePreferencesOverride();
  /**
   * <pre>
   * The override for the users locale preferences
   * </pre>
   *
   * <code>.api.commons.LocalePreferences locale_preferences_override = 15 [json_name = "localePreferencesOverride"];</code>
   */
  com.tcn.cloud.api.api.commons.LocalePreferencesOrBuilder getLocalePreferencesOverrideOrBuilder();

  /**
   * <pre>
   * Mask to filter fields on organization entities in response.
   * </pre>
   *
   * <code>repeated string field_mask = 20 [json_name = "fieldMask"];</code>
   * @return A list containing the fieldMask.
   */
  java.util.List<java.lang.String>
      getFieldMaskList();
  /**
   * <pre>
   * Mask to filter fields on organization entities in response.
   * </pre>
   *
   * <code>repeated string field_mask = 20 [json_name = "fieldMask"];</code>
   * @return The count of fieldMask.
   */
  int getFieldMaskCount();
  /**
   * <pre>
   * Mask to filter fields on organization entities in response.
   * </pre>
   *
   * <code>repeated string field_mask = 20 [json_name = "fieldMask"];</code>
   * @param index The index of the element to return.
   * @return The fieldMask at the given index.
   */
  java.lang.String getFieldMask(int index);
  /**
   * <pre>
   * Mask to filter fields on organization entities in response.
   * </pre>
   *
   * <code>repeated string field_mask = 20 [json_name = "fieldMask"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the fieldMask at the given index.
   */
  com.google.protobuf.ByteString
      getFieldMaskBytes(int index);
}
