// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/translations/v1alpha1/entities.proto

package com.tcn.cloud.api.services.translations.v1alpha1;

public interface ListContextsResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.translations.v1alpha1.ListContextsResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string contexts = 1 [json_name = "contexts"];</code>
   * @return A list containing the contexts.
   */
  java.util.List<java.lang.String>
      getContextsList();
  /**
   * <code>repeated string contexts = 1 [json_name = "contexts"];</code>
   * @return The count of contexts.
   */
  int getContextsCount();
  /**
   * <code>repeated string contexts = 1 [json_name = "contexts"];</code>
   * @param index The index of the element to return.
   * @return The contexts at the given index.
   */
  java.lang.String getContexts(int index);
  /**
   * <code>repeated string contexts = 1 [json_name = "contexts"];</code>
   * @param index The index of the value to return.
   * @return The bytes of the contexts at the given index.
   */
  com.google.protobuf.ByteString
      getContextsBytes(int index);
}
