// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v0alpha/callqueue.proto

package com.tcn.cloud.api.api.v0alpha;

/**
 * Protobuf type {@code api.v0alpha.EnqueueManuallyRejectedSmsReq}
 */
public final class EnqueueManuallyRejectedSmsReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.v0alpha.EnqueueManuallyRejectedSmsReq)
    EnqueueManuallyRejectedSmsReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use EnqueueManuallyRejectedSmsReq.newBuilder() to construct.
  private EnqueueManuallyRejectedSmsReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private EnqueueManuallyRejectedSmsReq() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new EnqueueManuallyRejectedSmsReq();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private EnqueueManuallyRejectedSmsReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.tcn.cloud.api.api.commons.SimpleSmsMamData.Builder subBuilder = null;
            if (sms_ != null) {
              subBuilder = sms_.toBuilder();
            }
            sms_ = input.readMessage(com.tcn.cloud.api.api.commons.SimpleSmsMamData.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(sms_);
              sms_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tcn.cloud.api.api.v0alpha.CallqueueProto.internal_static_api_v0alpha_EnqueueManuallyRejectedSmsReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tcn.cloud.api.api.v0alpha.CallqueueProto.internal_static_api_v0alpha_EnqueueManuallyRejectedSmsReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.class, com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.Builder.class);
  }

  public static final int SMS_FIELD_NUMBER = 1;
  private com.tcn.cloud.api.api.commons.SimpleSmsMamData sms_;
  /**
   * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
   * @return Whether the sms field is set.
   */
  @java.lang.Override
  public boolean hasSms() {
    return sms_ != null;
  }
  /**
   * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
   * @return The sms.
   */
  @java.lang.Override
  public com.tcn.cloud.api.api.commons.SimpleSmsMamData getSms() {
    return sms_ == null ? com.tcn.cloud.api.api.commons.SimpleSmsMamData.getDefaultInstance() : sms_;
  }
  /**
   * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
   */
  @java.lang.Override
  public com.tcn.cloud.api.api.commons.SimpleSmsMamDataOrBuilder getSmsOrBuilder() {
    return getSms();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (sms_ != null) {
      output.writeMessage(1, getSms());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (sms_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getSms());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq)) {
      return super.equals(obj);
    }
    com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq other = (com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq) obj;

    if (hasSms() != other.hasSms()) return false;
    if (hasSms()) {
      if (!getSms()
          .equals(other.getSms())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasSms()) {
      hash = (37 * hash) + SMS_FIELD_NUMBER;
      hash = (53 * hash) + getSms().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v0alpha.EnqueueManuallyRejectedSmsReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v0alpha.EnqueueManuallyRejectedSmsReq)
      com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tcn.cloud.api.api.v0alpha.CallqueueProto.internal_static_api_v0alpha_EnqueueManuallyRejectedSmsReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tcn.cloud.api.api.v0alpha.CallqueueProto.internal_static_api_v0alpha_EnqueueManuallyRejectedSmsReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.class, com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.Builder.class);
    }

    // Construct using com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (smsBuilder_ == null) {
        sms_ = null;
      } else {
        sms_ = null;
        smsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tcn.cloud.api.api.v0alpha.CallqueueProto.internal_static_api_v0alpha_EnqueueManuallyRejectedSmsReq_descriptor;
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq getDefaultInstanceForType() {
      return com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq build() {
      com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq buildPartial() {
      com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq result = new com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq(this);
      if (smsBuilder_ == null) {
        result.sms_ = sms_;
      } else {
        result.sms_ = smsBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq) {
        return mergeFrom((com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq other) {
      if (other == com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq.getDefaultInstance()) return this;
      if (other.hasSms()) {
        mergeSms(other.getSms());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.tcn.cloud.api.api.commons.SimpleSmsMamData sms_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tcn.cloud.api.api.commons.SimpleSmsMamData, com.tcn.cloud.api.api.commons.SimpleSmsMamData.Builder, com.tcn.cloud.api.api.commons.SimpleSmsMamDataOrBuilder> smsBuilder_;
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     * @return Whether the sms field is set.
     */
    public boolean hasSms() {
      return smsBuilder_ != null || sms_ != null;
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     * @return The sms.
     */
    public com.tcn.cloud.api.api.commons.SimpleSmsMamData getSms() {
      if (smsBuilder_ == null) {
        return sms_ == null ? com.tcn.cloud.api.api.commons.SimpleSmsMamData.getDefaultInstance() : sms_;
      } else {
        return smsBuilder_.getMessage();
      }
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    public Builder setSms(com.tcn.cloud.api.api.commons.SimpleSmsMamData value) {
      if (smsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        sms_ = value;
        onChanged();
      } else {
        smsBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    public Builder setSms(
        com.tcn.cloud.api.api.commons.SimpleSmsMamData.Builder builderForValue) {
      if (smsBuilder_ == null) {
        sms_ = builderForValue.build();
        onChanged();
      } else {
        smsBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    public Builder mergeSms(com.tcn.cloud.api.api.commons.SimpleSmsMamData value) {
      if (smsBuilder_ == null) {
        if (sms_ != null) {
          sms_ =
            com.tcn.cloud.api.api.commons.SimpleSmsMamData.newBuilder(sms_).mergeFrom(value).buildPartial();
        } else {
          sms_ = value;
        }
        onChanged();
      } else {
        smsBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    public Builder clearSms() {
      if (smsBuilder_ == null) {
        sms_ = null;
        onChanged();
      } else {
        sms_ = null;
        smsBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    public com.tcn.cloud.api.api.commons.SimpleSmsMamData.Builder getSmsBuilder() {
      
      onChanged();
      return getSmsFieldBuilder().getBuilder();
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    public com.tcn.cloud.api.api.commons.SimpleSmsMamDataOrBuilder getSmsOrBuilder() {
      if (smsBuilder_ != null) {
        return smsBuilder_.getMessageOrBuilder();
      } else {
        return sms_ == null ?
            com.tcn.cloud.api.api.commons.SimpleSmsMamData.getDefaultInstance() : sms_;
      }
    }
    /**
     * <code>.api.commons.SimpleSmsMamData sms = 1 [json_name = "sms"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tcn.cloud.api.api.commons.SimpleSmsMamData, com.tcn.cloud.api.api.commons.SimpleSmsMamData.Builder, com.tcn.cloud.api.api.commons.SimpleSmsMamDataOrBuilder> 
        getSmsFieldBuilder() {
      if (smsBuilder_ == null) {
        smsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tcn.cloud.api.api.commons.SimpleSmsMamData, com.tcn.cloud.api.api.commons.SimpleSmsMamData.Builder, com.tcn.cloud.api.api.commons.SimpleSmsMamDataOrBuilder>(
                getSms(),
                getParentForChildren(),
                isClean());
        sms_ = null;
      }
      return smsBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.v0alpha.EnqueueManuallyRejectedSmsReq)
  }

  // @@protoc_insertion_point(class_scope:api.v0alpha.EnqueueManuallyRejectedSmsReq)
  private static final com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq();
  }

  public static com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<EnqueueManuallyRejectedSmsReq>
      PARSER = new com.google.protobuf.AbstractParser<EnqueueManuallyRejectedSmsReq>() {
    @java.lang.Override
    public EnqueueManuallyRejectedSmsReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new EnqueueManuallyRejectedSmsReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<EnqueueManuallyRejectedSmsReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<EnqueueManuallyRejectedSmsReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tcn.cloud.api.api.v0alpha.EnqueueManuallyRejectedSmsReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

