// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v0alpha/compliance.proto

package com.tcn.cloud.api.api.v0alpha;

public interface GetScrubListUploadUrlResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v0alpha.GetScrubListUploadUrlRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The url.
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1 [json_name = "url"];</code>
   * @return The bytes for url.
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string filename = 2 [json_name = "filename"];</code>
   * @return The filename.
   */
  java.lang.String getFilename();
  /**
   * <code>string filename = 2 [json_name = "filename"];</code>
   * @return The bytes for filename.
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>string bucket = 3 [json_name = "bucket"];</code>
   * @return The bucket.
   */
  java.lang.String getBucket();
  /**
   * <code>string bucket = 3 [json_name = "bucket"];</code>
   * @return The bytes for bucket.
   */
  com.google.protobuf.ByteString
      getBucketBytes();
}
