// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v0alpha/ana.proto

package com.tcn.cloud.api.api.v0alpha;

/**
 * Protobuf type {@code api.v0alpha.IndicesVisibility}
 */
public final class IndicesVisibility extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.v0alpha.IndicesVisibility)
    IndicesVisibilityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IndicesVisibility.newBuilder() to construct.
  private IndicesVisibility(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IndicesVisibility() {
    visibilities_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IndicesVisibility();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tcn.cloud.api.api.v0alpha.AnaProto.internal_static_api_v0alpha_IndicesVisibility_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tcn.cloud.api.api.v0alpha.AnaProto.internal_static_api_v0alpha_IndicesVisibility_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tcn.cloud.api.api.v0alpha.IndicesVisibility.class, com.tcn.cloud.api.api.v0alpha.IndicesVisibility.Builder.class);
  }

  public static final int VISIBILITIES_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.tcn.cloud.api.api.v0alpha.IndexVisibility> visibilities_;
  /**
   * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tcn.cloud.api.api.v0alpha.IndexVisibility> getVisibilitiesList() {
    return visibilities_;
  }
  /**
   * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder> 
      getVisibilitiesOrBuilderList() {
    return visibilities_;
  }
  /**
   * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
   */
  @java.lang.Override
  public int getVisibilitiesCount() {
    return visibilities_.size();
  }
  /**
   * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
   */
  @java.lang.Override
  public com.tcn.cloud.api.api.v0alpha.IndexVisibility getVisibilities(int index) {
    return visibilities_.get(index);
  }
  /**
   * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
   */
  @java.lang.Override
  public com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder getVisibilitiesOrBuilder(
      int index) {
    return visibilities_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < visibilities_.size(); i++) {
      output.writeMessage(1, visibilities_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < visibilities_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, visibilities_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tcn.cloud.api.api.v0alpha.IndicesVisibility)) {
      return super.equals(obj);
    }
    com.tcn.cloud.api.api.v0alpha.IndicesVisibility other = (com.tcn.cloud.api.api.v0alpha.IndicesVisibility) obj;

    if (!getVisibilitiesList()
        .equals(other.getVisibilitiesList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getVisibilitiesCount() > 0) {
      hash = (37 * hash) + VISIBILITIES_FIELD_NUMBER;
      hash = (53 * hash) + getVisibilitiesList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tcn.cloud.api.api.v0alpha.IndicesVisibility prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code api.v0alpha.IndicesVisibility}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v0alpha.IndicesVisibility)
      com.tcn.cloud.api.api.v0alpha.IndicesVisibilityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tcn.cloud.api.api.v0alpha.AnaProto.internal_static_api_v0alpha_IndicesVisibility_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tcn.cloud.api.api.v0alpha.AnaProto.internal_static_api_v0alpha_IndicesVisibility_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tcn.cloud.api.api.v0alpha.IndicesVisibility.class, com.tcn.cloud.api.api.v0alpha.IndicesVisibility.Builder.class);
    }

    // Construct using com.tcn.cloud.api.api.v0alpha.IndicesVisibility.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (visibilitiesBuilder_ == null) {
        visibilities_ = java.util.Collections.emptyList();
      } else {
        visibilities_ = null;
        visibilitiesBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tcn.cloud.api.api.v0alpha.AnaProto.internal_static_api_v0alpha_IndicesVisibility_descriptor;
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v0alpha.IndicesVisibility getDefaultInstanceForType() {
      return com.tcn.cloud.api.api.v0alpha.IndicesVisibility.getDefaultInstance();
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v0alpha.IndicesVisibility build() {
      com.tcn.cloud.api.api.v0alpha.IndicesVisibility result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v0alpha.IndicesVisibility buildPartial() {
      com.tcn.cloud.api.api.v0alpha.IndicesVisibility result = new com.tcn.cloud.api.api.v0alpha.IndicesVisibility(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tcn.cloud.api.api.v0alpha.IndicesVisibility result) {
      if (visibilitiesBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          visibilities_ = java.util.Collections.unmodifiableList(visibilities_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.visibilities_ = visibilities_;
      } else {
        result.visibilities_ = visibilitiesBuilder_.build();
      }
    }

    private void buildPartial0(com.tcn.cloud.api.api.v0alpha.IndicesVisibility result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tcn.cloud.api.api.v0alpha.IndicesVisibility) {
        return mergeFrom((com.tcn.cloud.api.api.v0alpha.IndicesVisibility)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tcn.cloud.api.api.v0alpha.IndicesVisibility other) {
      if (other == com.tcn.cloud.api.api.v0alpha.IndicesVisibility.getDefaultInstance()) return this;
      if (visibilitiesBuilder_ == null) {
        if (!other.visibilities_.isEmpty()) {
          if (visibilities_.isEmpty()) {
            visibilities_ = other.visibilities_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureVisibilitiesIsMutable();
            visibilities_.addAll(other.visibilities_);
          }
          onChanged();
        }
      } else {
        if (!other.visibilities_.isEmpty()) {
          if (visibilitiesBuilder_.isEmpty()) {
            visibilitiesBuilder_.dispose();
            visibilitiesBuilder_ = null;
            visibilities_ = other.visibilities_;
            bitField0_ = (bitField0_ & ~0x00000001);
            visibilitiesBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getVisibilitiesFieldBuilder() : null;
          } else {
            visibilitiesBuilder_.addAllMessages(other.visibilities_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.tcn.cloud.api.api.v0alpha.IndexVisibility m =
                  input.readMessage(
                      com.tcn.cloud.api.api.v0alpha.IndexVisibility.parser(),
                      extensionRegistry);
              if (visibilitiesBuilder_ == null) {
                ensureVisibilitiesIsMutable();
                visibilities_.add(m);
              } else {
                visibilitiesBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.tcn.cloud.api.api.v0alpha.IndexVisibility> visibilities_ =
      java.util.Collections.emptyList();
    private void ensureVisibilitiesIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        visibilities_ = new java.util.ArrayList<com.tcn.cloud.api.api.v0alpha.IndexVisibility>(visibilities_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tcn.cloud.api.api.v0alpha.IndexVisibility, com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder, com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder> visibilitiesBuilder_;

    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public java.util.List<com.tcn.cloud.api.api.v0alpha.IndexVisibility> getVisibilitiesList() {
      if (visibilitiesBuilder_ == null) {
        return java.util.Collections.unmodifiableList(visibilities_);
      } else {
        return visibilitiesBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public int getVisibilitiesCount() {
      if (visibilitiesBuilder_ == null) {
        return visibilities_.size();
      } else {
        return visibilitiesBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public com.tcn.cloud.api.api.v0alpha.IndexVisibility getVisibilities(int index) {
      if (visibilitiesBuilder_ == null) {
        return visibilities_.get(index);
      } else {
        return visibilitiesBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder setVisibilities(
        int index, com.tcn.cloud.api.api.v0alpha.IndexVisibility value) {
      if (visibilitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisibilitiesIsMutable();
        visibilities_.set(index, value);
        onChanged();
      } else {
        visibilitiesBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder setVisibilities(
        int index, com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder builderForValue) {
      if (visibilitiesBuilder_ == null) {
        ensureVisibilitiesIsMutable();
        visibilities_.set(index, builderForValue.build());
        onChanged();
      } else {
        visibilitiesBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder addVisibilities(com.tcn.cloud.api.api.v0alpha.IndexVisibility value) {
      if (visibilitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisibilitiesIsMutable();
        visibilities_.add(value);
        onChanged();
      } else {
        visibilitiesBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder addVisibilities(
        int index, com.tcn.cloud.api.api.v0alpha.IndexVisibility value) {
      if (visibilitiesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVisibilitiesIsMutable();
        visibilities_.add(index, value);
        onChanged();
      } else {
        visibilitiesBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder addVisibilities(
        com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder builderForValue) {
      if (visibilitiesBuilder_ == null) {
        ensureVisibilitiesIsMutable();
        visibilities_.add(builderForValue.build());
        onChanged();
      } else {
        visibilitiesBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder addVisibilities(
        int index, com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder builderForValue) {
      if (visibilitiesBuilder_ == null) {
        ensureVisibilitiesIsMutable();
        visibilities_.add(index, builderForValue.build());
        onChanged();
      } else {
        visibilitiesBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder addAllVisibilities(
        java.lang.Iterable<? extends com.tcn.cloud.api.api.v0alpha.IndexVisibility> values) {
      if (visibilitiesBuilder_ == null) {
        ensureVisibilitiesIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, visibilities_);
        onChanged();
      } else {
        visibilitiesBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder clearVisibilities() {
      if (visibilitiesBuilder_ == null) {
        visibilities_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        visibilitiesBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public Builder removeVisibilities(int index) {
      if (visibilitiesBuilder_ == null) {
        ensureVisibilitiesIsMutable();
        visibilities_.remove(index);
        onChanged();
      } else {
        visibilitiesBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder getVisibilitiesBuilder(
        int index) {
      return getVisibilitiesFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder getVisibilitiesOrBuilder(
        int index) {
      if (visibilitiesBuilder_ == null) {
        return visibilities_.get(index);  } else {
        return visibilitiesBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public java.util.List<? extends com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder> 
         getVisibilitiesOrBuilderList() {
      if (visibilitiesBuilder_ != null) {
        return visibilitiesBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(visibilities_);
      }
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder addVisibilitiesBuilder() {
      return getVisibilitiesFieldBuilder().addBuilder(
          com.tcn.cloud.api.api.v0alpha.IndexVisibility.getDefaultInstance());
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder addVisibilitiesBuilder(
        int index) {
      return getVisibilitiesFieldBuilder().addBuilder(
          index, com.tcn.cloud.api.api.v0alpha.IndexVisibility.getDefaultInstance());
    }
    /**
     * <code>repeated .api.v0alpha.IndexVisibility visibilities = 1 [json_name = "visibilities"];</code>
     */
    public java.util.List<com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder> 
         getVisibilitiesBuilderList() {
      return getVisibilitiesFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tcn.cloud.api.api.v0alpha.IndexVisibility, com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder, com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder> 
        getVisibilitiesFieldBuilder() {
      if (visibilitiesBuilder_ == null) {
        visibilitiesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tcn.cloud.api.api.v0alpha.IndexVisibility, com.tcn.cloud.api.api.v0alpha.IndexVisibility.Builder, com.tcn.cloud.api.api.v0alpha.IndexVisibilityOrBuilder>(
                visibilities_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        visibilities_ = null;
      }
      return visibilitiesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.v0alpha.IndicesVisibility)
  }

  // @@protoc_insertion_point(class_scope:api.v0alpha.IndicesVisibility)
  private static final com.tcn.cloud.api.api.v0alpha.IndicesVisibility DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tcn.cloud.api.api.v0alpha.IndicesVisibility();
  }

  public static com.tcn.cloud.api.api.v0alpha.IndicesVisibility getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<IndicesVisibility>
      PARSER = new com.google.protobuf.AbstractParser<IndicesVisibility>() {
    @java.lang.Override
    public IndicesVisibility parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<IndicesVisibility> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IndicesVisibility> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tcn.cloud.api.api.v0alpha.IndicesVisibility getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

