// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v0alpha/emailapi.proto

package com.tcn.cloud.api.api.v0alpha;

public interface UpdateOutboundEmailGroupReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v0alpha.UpdateOutboundEmailGroupReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *outbound email group sid
   * </pre>
   *
   * <code>int64 email_group_sid = 1 [json_name = "emailGroupSid"];</code>
   * @return The emailGroupSid.
   */
  long getEmailGroupSid();

  /**
   * <pre>
   *name of the email group
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <pre>
   *name of the email group
   * </pre>
   *
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   *time when outbound email group needs to be started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 3 [json_name = "startTime"];</code>
   * @return Whether the startTime field is set.
   */
  boolean hasStartTime();
  /**
   * <pre>
   *time when outbound email group needs to be started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 3 [json_name = "startTime"];</code>
   * @return The startTime.
   */
  com.google.protobuf.Timestamp getStartTime();
  /**
   * <pre>
   *time when outbound email group needs to be started
   * </pre>
   *
   * <code>.google.protobuf.Timestamp start_time = 3 [json_name = "startTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getStartTimeOrBuilder();

  /**
   * <pre>
   *time when outbound email group needs to be stopped
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 4 [json_name = "stopTime"];</code>
   * @return Whether the stopTime field is set.
   */
  boolean hasStopTime();
  /**
   * <pre>
   *time when outbound email group needs to be stopped
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 4 [json_name = "stopTime"];</code>
   * @return The stopTime.
   */
  com.google.protobuf.Timestamp getStopTime();
  /**
   * <pre>
   *time when outbound email group needs to be stopped
   * </pre>
   *
   * <code>.google.protobuf.Timestamp stop_time = 4 [json_name = "stopTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getStopTimeOrBuilder();

  /**
   * <pre>
   *description of the email group
   * </pre>
   *
   * <code>string description = 6 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <pre>
   *description of the email group
   * </pre>
   *
   * <code>string description = 6 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * sla and timeouts
   * </pre>
   *
   * <code>.api.commons.SLATimeouts sla_timeouts = 7 [json_name = "slaTimeouts"];</code>
   * @return Whether the slaTimeouts field is set.
   */
  boolean hasSlaTimeouts();
  /**
   * <pre>
   * sla and timeouts
   * </pre>
   *
   * <code>.api.commons.SLATimeouts sla_timeouts = 7 [json_name = "slaTimeouts"];</code>
   * @return The slaTimeouts.
   */
  com.tcn.cloud.api.api.commons.SLATimeouts getSlaTimeouts();
  /**
   * <pre>
   * sla and timeouts
   * </pre>
   *
   * <code>.api.commons.SLATimeouts sla_timeouts = 7 [json_name = "slaTimeouts"];</code>
   */
  com.tcn.cloud.api.api.commons.SLATimeoutsOrBuilder getSlaTimeoutsOrBuilder();
}
