// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/billing/entities/v1alpha4/rates.proto

package com.tcn.cloud.api.services.billing.entities.v1alpha4;

public interface MatchingRuleOrBuilder extends
    // @@protoc_insertion_point(interface_extends:services.billing.entities.v1alpha4.MatchingRule)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string matching_rule_id = 1 [json_name = "matchingRuleId"];</code>
   * @return The matchingRuleId.
   */
  java.lang.String getMatchingRuleId();
  /**
   * <code>string matching_rule_id = 1 [json_name = "matchingRuleId"];</code>
   * @return The bytes for matchingRuleId.
   */
  com.google.protobuf.ByteString
      getMatchingRuleIdBytes();

  /**
   * <code>.services.billing.entities.v1alpha4.ProductConfig config = 2 [json_name = "config", deprecated = true];</code>
   * @deprecated services.billing.entities.v1alpha4.MatchingRule.config is deprecated.
   *     See services/billing/entities/v1alpha4/rates.proto;l=24
   * @return Whether the config field is set.
   */
  @java.lang.Deprecated boolean hasConfig();
  /**
   * <code>.services.billing.entities.v1alpha4.ProductConfig config = 2 [json_name = "config", deprecated = true];</code>
   * @deprecated services.billing.entities.v1alpha4.MatchingRule.config is deprecated.
   *     See services/billing/entities/v1alpha4/rates.proto;l=24
   * @return The config.
   */
  @java.lang.Deprecated com.tcn.cloud.api.services.billing.entities.v1alpha4.ProductConfig getConfig();
  /**
   * <code>.services.billing.entities.v1alpha4.ProductConfig config = 2 [json_name = "config", deprecated = true];</code>
   */
  @java.lang.Deprecated com.tcn.cloud.api.services.billing.entities.v1alpha4.ProductConfigOrBuilder getConfigOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp create_time = 3 [json_name = "createTime"];</code>
   * @return Whether the createTime field is set.
   */
  boolean hasCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 3 [json_name = "createTime"];</code>
   * @return The createTime.
   */
  com.google.protobuf.Timestamp getCreateTime();
  /**
   * <code>.google.protobuf.Timestamp create_time = 3 [json_name = "createTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp delete_time = 4 [json_name = "deleteTime"];</code>
   * @return Whether the deleteTime field is set.
   */
  boolean hasDeleteTime();
  /**
   * <code>.google.protobuf.Timestamp delete_time = 4 [json_name = "deleteTime"];</code>
   * @return The deleteTime.
   */
  com.google.protobuf.Timestamp getDeleteTime();
  /**
   * <code>.google.protobuf.Timestamp delete_time = 4 [json_name = "deleteTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getDeleteTimeOrBuilder();

  /**
   * <code>.google.protobuf.Timestamp update_time = 5 [json_name = "updateTime"];</code>
   * @return Whether the updateTime field is set.
   */
  boolean hasUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp update_time = 5 [json_name = "updateTime"];</code>
   * @return The updateTime.
   */
  com.google.protobuf.Timestamp getUpdateTime();
  /**
   * <code>.google.protobuf.Timestamp update_time = 5 [json_name = "updateTime"];</code>
   */
  com.google.protobuf.TimestampOrBuilder getUpdateTimeOrBuilder();

  /**
   * <code>.services.billing.entities.v1alpha4.MatchingConfig rule_config = 6 [json_name = "ruleConfig"];</code>
   * @return Whether the ruleConfig field is set.
   */
  boolean hasRuleConfig();
  /**
   * <code>.services.billing.entities.v1alpha4.MatchingConfig rule_config = 6 [json_name = "ruleConfig"];</code>
   * @return The ruleConfig.
   */
  com.tcn.cloud.api.services.billing.entities.v1alpha4.MatchingConfig getRuleConfig();
  /**
   * <code>.services.billing.entities.v1alpha4.MatchingConfig rule_config = 6 [json_name = "ruleConfig"];</code>
   */
  com.tcn.cloud.api.services.billing.entities.v1alpha4.MatchingConfigOrBuilder getRuleConfigOrBuilder();

  /**
   * <code>.services.billing.entities.v1alpha4.CountryCodePrefix country_code_prefix = 100 [json_name = "countryCodePrefix", deprecated = true];</code>
   * @deprecated services.billing.entities.v1alpha4.MatchingRule.country_code_prefix is deprecated.
   *     See services/billing/entities/v1alpha4/rates.proto;l=30
   * @return Whether the countryCodePrefix field is set.
   */
  @java.lang.Deprecated boolean hasCountryCodePrefix();
  /**
   * <code>.services.billing.entities.v1alpha4.CountryCodePrefix country_code_prefix = 100 [json_name = "countryCodePrefix", deprecated = true];</code>
   * @deprecated services.billing.entities.v1alpha4.MatchingRule.country_code_prefix is deprecated.
   *     See services/billing/entities/v1alpha4/rates.proto;l=30
   * @return The countryCodePrefix.
   */
  @java.lang.Deprecated com.tcn.cloud.api.services.billing.entities.v1alpha4.CountryCodePrefix getCountryCodePrefix();
  /**
   * <code>.services.billing.entities.v1alpha4.CountryCodePrefix country_code_prefix = 100 [json_name = "countryCodePrefix", deprecated = true];</code>
   */
  @java.lang.Deprecated com.tcn.cloud.api.services.billing.entities.v1alpha4.CountryCodePrefixOrBuilder getCountryCodePrefixOrBuilder();

  com.tcn.cloud.api.services.billing.entities.v1alpha4.MatchingRule.MatchingConfigCase getMatchingConfigCase();
}
