// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/wfm/wfm.proto

package com.tcn.cloud.api.api.v1alpha1.wfm;

/**
 * <pre>
 * Request message for the GetTourPattern RPC.
 * </pre>
 *
 * Protobuf type {@code api.v1alpha1.wfm.GetTourPatternRes}
 */
public final class GetTourPatternRes extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:api.v1alpha1.wfm.GetTourPatternRes)
    GetTourPatternResOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetTourPatternRes.newBuilder() to construct.
  private GetTourPatternRes(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetTourPatternRes() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetTourPatternRes();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tcn.cloud.api.api.v1alpha1.wfm.WfmProto.internal_static_api_v1alpha1_wfm_GetTourPatternRes_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tcn.cloud.api.api.v1alpha1.wfm.WfmProto.internal_static_api_v1alpha1_wfm_GetTourPatternRes_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.class, com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.Builder.class);
  }

  public static final int TOUR_PATTERN_FIELD_NUMBER = 1;
  private com.tcn.cloud.api.api.commons.TourPattern tourPattern_;
  /**
   * <pre>
   * The requested Tour Pattern
   * </pre>
   *
   * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
   * @return Whether the tourPattern field is set.
   */
  @java.lang.Override
  public boolean hasTourPattern() {
    return tourPattern_ != null;
  }
  /**
   * <pre>
   * The requested Tour Pattern
   * </pre>
   *
   * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
   * @return The tourPattern.
   */
  @java.lang.Override
  public com.tcn.cloud.api.api.commons.TourPattern getTourPattern() {
    return tourPattern_ == null ? com.tcn.cloud.api.api.commons.TourPattern.getDefaultInstance() : tourPattern_;
  }
  /**
   * <pre>
   * The requested Tour Pattern
   * </pre>
   *
   * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
   */
  @java.lang.Override
  public com.tcn.cloud.api.api.commons.TourPatternOrBuilder getTourPatternOrBuilder() {
    return tourPattern_ == null ? com.tcn.cloud.api.api.commons.TourPattern.getDefaultInstance() : tourPattern_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (tourPattern_ != null) {
      output.writeMessage(1, getTourPattern());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (tourPattern_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getTourPattern());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes)) {
      return super.equals(obj);
    }
    com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes other = (com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes) obj;

    if (hasTourPattern() != other.hasTourPattern()) return false;
    if (hasTourPattern()) {
      if (!getTourPattern()
          .equals(other.getTourPattern())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasTourPattern()) {
      hash = (37 * hash) + TOUR_PATTERN_FIELD_NUMBER;
      hash = (53 * hash) + getTourPattern().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Request message for the GetTourPattern RPC.
   * </pre>
   *
   * Protobuf type {@code api.v1alpha1.wfm.GetTourPatternRes}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:api.v1alpha1.wfm.GetTourPatternRes)
      com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternResOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tcn.cloud.api.api.v1alpha1.wfm.WfmProto.internal_static_api_v1alpha1_wfm_GetTourPatternRes_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tcn.cloud.api.api.v1alpha1.wfm.WfmProto.internal_static_api_v1alpha1_wfm_GetTourPatternRes_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.class, com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.Builder.class);
    }

    // Construct using com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      tourPattern_ = null;
      if (tourPatternBuilder_ != null) {
        tourPatternBuilder_.dispose();
        tourPatternBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tcn.cloud.api.api.v1alpha1.wfm.WfmProto.internal_static_api_v1alpha1_wfm_GetTourPatternRes_descriptor;
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes getDefaultInstanceForType() {
      return com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.getDefaultInstance();
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes build() {
      com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes buildPartial() {
      com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes result = new com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.tourPattern_ = tourPatternBuilder_ == null
            ? tourPattern_
            : tourPatternBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes) {
        return mergeFrom((com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes other) {
      if (other == com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes.getDefaultInstance()) return this;
      if (other.hasTourPattern()) {
        mergeTourPattern(other.getTourPattern());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  getTourPatternFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.tcn.cloud.api.api.commons.TourPattern tourPattern_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tcn.cloud.api.api.commons.TourPattern, com.tcn.cloud.api.api.commons.TourPattern.Builder, com.tcn.cloud.api.api.commons.TourPatternOrBuilder> tourPatternBuilder_;
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     * @return Whether the tourPattern field is set.
     */
    public boolean hasTourPattern() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     * @return The tourPattern.
     */
    public com.tcn.cloud.api.api.commons.TourPattern getTourPattern() {
      if (tourPatternBuilder_ == null) {
        return tourPattern_ == null ? com.tcn.cloud.api.api.commons.TourPattern.getDefaultInstance() : tourPattern_;
      } else {
        return tourPatternBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    public Builder setTourPattern(com.tcn.cloud.api.api.commons.TourPattern value) {
      if (tourPatternBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        tourPattern_ = value;
      } else {
        tourPatternBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    public Builder setTourPattern(
        com.tcn.cloud.api.api.commons.TourPattern.Builder builderForValue) {
      if (tourPatternBuilder_ == null) {
        tourPattern_ = builderForValue.build();
      } else {
        tourPatternBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    public Builder mergeTourPattern(com.tcn.cloud.api.api.commons.TourPattern value) {
      if (tourPatternBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          tourPattern_ != null &&
          tourPattern_ != com.tcn.cloud.api.api.commons.TourPattern.getDefaultInstance()) {
          getTourPatternBuilder().mergeFrom(value);
        } else {
          tourPattern_ = value;
        }
      } else {
        tourPatternBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    public Builder clearTourPattern() {
      bitField0_ = (bitField0_ & ~0x00000001);
      tourPattern_ = null;
      if (tourPatternBuilder_ != null) {
        tourPatternBuilder_.dispose();
        tourPatternBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    public com.tcn.cloud.api.api.commons.TourPattern.Builder getTourPatternBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return getTourPatternFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    public com.tcn.cloud.api.api.commons.TourPatternOrBuilder getTourPatternOrBuilder() {
      if (tourPatternBuilder_ != null) {
        return tourPatternBuilder_.getMessageOrBuilder();
      } else {
        return tourPattern_ == null ?
            com.tcn.cloud.api.api.commons.TourPattern.getDefaultInstance() : tourPattern_;
      }
    }
    /**
     * <pre>
     * The requested Tour Pattern
     * </pre>
     *
     * <code>.api.commons.TourPattern tour_pattern = 1 [json_name = "tourPattern"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.tcn.cloud.api.api.commons.TourPattern, com.tcn.cloud.api.api.commons.TourPattern.Builder, com.tcn.cloud.api.api.commons.TourPatternOrBuilder> 
        getTourPatternFieldBuilder() {
      if (tourPatternBuilder_ == null) {
        tourPatternBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.tcn.cloud.api.api.commons.TourPattern, com.tcn.cloud.api.api.commons.TourPattern.Builder, com.tcn.cloud.api.api.commons.TourPatternOrBuilder>(
                getTourPattern(),
                getParentForChildren(),
                isClean());
        tourPattern_ = null;
      }
      return tourPatternBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:api.v1alpha1.wfm.GetTourPatternRes)
  }

  // @@protoc_insertion_point(class_scope:api.v1alpha1.wfm.GetTourPatternRes)
  private static final com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes();
  }

  public static com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetTourPatternRes>
      PARSER = new com.google.protobuf.AbstractParser<GetTourPatternRes>() {
    @java.lang.Override
    public GetTourPatternRes parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<GetTourPatternRes> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetTourPatternRes> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tcn.cloud.api.api.v1alpha1.wfm.GetTourPatternRes getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

