// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/wfm/wfm.proto

package com.tcn.cloud.api.api.v1alpha1.wfm;

public interface ListShiftTemplatesBySidsResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1alpha1.wfm.ListShiftTemplatesBySidsRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Requested shift templates.
   * </pre>
   *
   * <code>repeated .api.v1alpha1.wfm.ShiftTemplate shift_templates = 1 [json_name = "shiftTemplates"];</code>
   */
  java.util.List<com.tcn.cloud.api.api.v1alpha1.wfm.ShiftTemplate> 
      getShiftTemplatesList();
  /**
   * <pre>
   * Requested shift templates.
   * </pre>
   *
   * <code>repeated .api.v1alpha1.wfm.ShiftTemplate shift_templates = 1 [json_name = "shiftTemplates"];</code>
   */
  com.tcn.cloud.api.api.v1alpha1.wfm.ShiftTemplate getShiftTemplates(int index);
  /**
   * <pre>
   * Requested shift templates.
   * </pre>
   *
   * <code>repeated .api.v1alpha1.wfm.ShiftTemplate shift_templates = 1 [json_name = "shiftTemplates"];</code>
   */
  int getShiftTemplatesCount();
  /**
   * <pre>
   * Requested shift templates.
   * </pre>
   *
   * <code>repeated .api.v1alpha1.wfm.ShiftTemplate shift_templates = 1 [json_name = "shiftTemplates"];</code>
   */
  java.util.List<? extends com.tcn.cloud.api.api.v1alpha1.wfm.ShiftTemplateOrBuilder> 
      getShiftTemplatesOrBuilderList();
  /**
   * <pre>
   * Requested shift templates.
   * </pre>
   *
   * <code>repeated .api.v1alpha1.wfm.ShiftTemplate shift_templates = 1 [json_name = "shiftTemplates"];</code>
   */
  com.tcn.cloud.api.api.v1alpha1.wfm.ShiftTemplateOrBuilder getShiftTemplatesOrBuilder(
      int index);
}
