// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/v1alpha1/wfm/wfm.proto

package com.tcn.cloud.api.api.v1alpha1.wfm;

public interface ListValidAgentsForReplacementReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.v1alpha1.wfm.ListValidAgentsForReplacementReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the schedule scenario to check for WFM agents.
   * </pre>
   *
   * <code>int64 schedule_scenario_sid = 1 [json_name = "scheduleScenarioSid"];</code>
   * @return The scheduleScenarioSid.
   */
  long getScheduleScenarioSid();

  /**
   * <pre>
   * An optional field used to limit the datetime range of the shifts being checked.
   * If left blank, the full schedule range will be updated.
   * </pre>
   *
   * <code>.api.commons.DatetimeRange datetime_range = 2 [json_name = "datetimeRange"];</code>
   * @return Whether the datetimeRange field is set.
   */
  boolean hasDatetimeRange();
  /**
   * <pre>
   * An optional field used to limit the datetime range of the shifts being checked.
   * If left blank, the full schedule range will be updated.
   * </pre>
   *
   * <code>.api.commons.DatetimeRange datetime_range = 2 [json_name = "datetimeRange"];</code>
   * @return The datetimeRange.
   */
  com.tcn.cloud.api.api.commons.DatetimeRange getDatetimeRange();
  /**
   * <pre>
   * An optional field used to limit the datetime range of the shifts being checked.
   * If left blank, the full schedule range will be updated.
   * </pre>
   *
   * <code>.api.commons.DatetimeRange datetime_range = 2 [json_name = "datetimeRange"];</code>
   */
  com.tcn.cloud.api.api.commons.DatetimeRangeOrBuilder getDatetimeRangeOrBuilder();

  /**
   * <pre>
   * Indicates the schedule to be updated.
   * </pre>
   *
   * <code>.api.commons.ScheduleSelector schedule_selector = 3 [json_name = "scheduleSelector"];</code>
   * @return Whether the scheduleSelector field is set.
   */
  boolean hasScheduleSelector();
  /**
   * <pre>
   * Indicates the schedule to be updated.
   * </pre>
   *
   * <code>.api.commons.ScheduleSelector schedule_selector = 3 [json_name = "scheduleSelector"];</code>
   * @return The scheduleSelector.
   */
  com.tcn.cloud.api.api.commons.ScheduleSelector getScheduleSelector();
  /**
   * <pre>
   * Indicates the schedule to be updated.
   * </pre>
   *
   * <code>.api.commons.ScheduleSelector schedule_selector = 3 [json_name = "scheduleSelector"];</code>
   */
  com.tcn.cloud.api.api.commons.ScheduleSelectorOrBuilder getScheduleSelectorOrBuilder();

  /**
   * <pre>
   * An optional field indicating the node to get shifts from.
   * Otherwise shifts will be checked for all nodes on the &#64;schedule_selector.
   * </pre>
   *
   * <code>.api.v1alpha1.wfm.ParentEntity node_selector = 4 [json_name = "nodeSelector"];</code>
   * @return Whether the nodeSelector field is set.
   */
  boolean hasNodeSelector();
  /**
   * <pre>
   * An optional field indicating the node to get shifts from.
   * Otherwise shifts will be checked for all nodes on the &#64;schedule_selector.
   * </pre>
   *
   * <code>.api.v1alpha1.wfm.ParentEntity node_selector = 4 [json_name = "nodeSelector"];</code>
   * @return The nodeSelector.
   */
  com.tcn.cloud.api.api.v1alpha1.wfm.ParentEntity getNodeSelector();
  /**
   * <pre>
   * An optional field indicating the node to get shifts from.
   * Otherwise shifts will be checked for all nodes on the &#64;schedule_selector.
   * </pre>
   *
   * <code>.api.v1alpha1.wfm.ParentEntity node_selector = 4 [json_name = "nodeSelector"];</code>
   */
  com.tcn.cloud.api.api.v1alpha1.wfm.ParentEntityOrBuilder getNodeSelectorOrBuilder();

  /**
   * <pre>
   * ID of the WFM Agent to be replaced.
   * </pre>
   *
   * <code>int64 wfm_agent_sid_to_replace = 5 [json_name = "wfmAgentSidToReplace"];</code>
   * @return The wfmAgentSidToReplace.
   */
  long getWfmAgentSidToReplace();

  /**
   * <pre>
   * Indicates whether the step to sort agents by skill proficiency should be skipped.
   * If left as False, the &#64;wfm_agent_sids will be returned in descending order from most qualified to least qualified.
   * </pre>
   *
   * <code>bool skip_skill_proficiency_sort = 6 [json_name = "skipSkillProficiencySort"];</code>
   * @return The skipSkillProficiencySort.
   */
  boolean getSkipSkillProficiencySort();

  /**
   * <pre>
   * Indicated whether agent sids should still be returned, even if they do not have a skill proficiency for all of the required skills.
   * If left as False, only agents with a skill proficiency for all the updted shifts will be returned.
   * Under no conditions are constraint rule requirements enforced by this endpoint.
   * </pre>
   *
   * <code>bool include_skill_mismatches = 7 [json_name = "includeSkillMismatches"];</code>
   * @return The includeSkillMismatches.
   */
  boolean getIncludeSkillMismatches();

  /**
   * <pre>
   * Indicated whether to skip the check for must be members of all of the same agent groups as &#64;
   * </pre>
   *
   * <code>bool skip_force_same_agent_groups = 8 [json_name = "skipForceSameAgentGroups"];</code>
   * @return The skipForceSameAgentGroups.
   */
  boolean getSkipForceSameAgentGroups();
}
