// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: api/commons/compliance.proto

package com.tcn.cloud.api.api.commons;

public interface DispositionModOrBuilder extends
    // @@protoc_insertion_point(interface_extends:api.commons.DispositionMod)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .api.commons.DispositionField dispositions = 1 [json_name = "dispositions"];</code>
   */
  java.util.List<com.tcn.cloud.api.api.commons.DispositionField> 
      getDispositionsList();
  /**
   * <code>repeated .api.commons.DispositionField dispositions = 1 [json_name = "dispositions"];</code>
   */
  com.tcn.cloud.api.api.commons.DispositionField getDispositions(int index);
  /**
   * <code>repeated .api.commons.DispositionField dispositions = 1 [json_name = "dispositions"];</code>
   */
  int getDispositionsCount();
  /**
   * <code>repeated .api.commons.DispositionField dispositions = 1 [json_name = "dispositions"];</code>
   */
  java.util.List<? extends com.tcn.cloud.api.api.commons.DispositionFieldOrBuilder> 
      getDispositionsOrBuilderList();
  /**
   * <code>repeated .api.commons.DispositionField dispositions = 1 [json_name = "dispositions"];</code>
   */
  com.tcn.cloud.api.api.commons.DispositionFieldOrBuilder getDispositionsOrBuilder(
      int index);
}
