// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: services/billing/entities/v1alpha2/invoice.proto

package com.tcn.cloud.api.services.billing.entities.v1alpha2;

/**
 * Protobuf type {@code services.billing.entities.v1alpha2.Invoice}
 */
public final class Invoice extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:services.billing.entities.v1alpha2.Invoice)
    InvoiceOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Invoice.newBuilder() to construct.
  private Invoice(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Invoice() {
    billingCycle_ = "";
    items_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Invoice();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceProto.internal_static_services_billing_entities_v1alpha2_Invoice_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceProto.internal_static_services_billing_entities_v1alpha2_Invoice_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.class, com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.Builder.class);
  }

  public static final int BILLING_CYCLE_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object billingCycle_ = "";
  /**
   * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
   * @return The billingCycle.
   */
  @java.lang.Override
  public java.lang.String getBillingCycle() {
    java.lang.Object ref = billingCycle_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      billingCycle_ = s;
      return s;
    }
  }
  /**
   * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
   * @return The bytes for billingCycle.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBillingCycleBytes() {
    java.lang.Object ref = billingCycle_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      billingCycle_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CREATE_TIME_FIELD_NUMBER = 2;
  private com.google.protobuf.Timestamp createTime_;
  /**
   * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
   * @return Whether the createTime field is set.
   */
  @java.lang.Override
  public boolean hasCreateTime() {
    return createTime_ != null;
  }
  /**
   * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
   * @return The createTime.
   */
  @java.lang.Override
  public com.google.protobuf.Timestamp getCreateTime() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }
  /**
   * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
    return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
  }

  public static final int ITEMS_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem> items_;
  /**
   * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem> getItemsList() {
    return items_;
  }
  /**
   * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
   */
  @java.lang.Override
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
   */
  @java.lang.Override
  public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
   */
  @java.lang.Override
  public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int DOWNLOAD_URL_FIELD_NUMBER = 4;
  private com.google.protobuf.StringValue downloadUrl_;
  /**
   * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
   * @return Whether the downloadUrl field is set.
   */
  @java.lang.Override
  public boolean hasDownloadUrl() {
    return downloadUrl_ != null;
  }
  /**
   * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
   * @return The downloadUrl.
   */
  @java.lang.Override
  public com.google.protobuf.StringValue getDownloadUrl() {
    return downloadUrl_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : downloadUrl_;
  }
  /**
   * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
   */
  @java.lang.Override
  public com.google.protobuf.StringValueOrBuilder getDownloadUrlOrBuilder() {
    return downloadUrl_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : downloadUrl_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(billingCycle_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, billingCycle_);
    }
    if (createTime_ != null) {
      output.writeMessage(2, getCreateTime());
    }
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(3, items_.get(i));
    }
    if (downloadUrl_ != null) {
      output.writeMessage(4, getDownloadUrl());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(billingCycle_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, billingCycle_);
    }
    if (createTime_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getCreateTime());
    }
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, items_.get(i));
    }
    if (downloadUrl_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, getDownloadUrl());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice)) {
      return super.equals(obj);
    }
    com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice other = (com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice) obj;

    if (!getBillingCycle()
        .equals(other.getBillingCycle())) return false;
    if (hasCreateTime() != other.hasCreateTime()) return false;
    if (hasCreateTime()) {
      if (!getCreateTime()
          .equals(other.getCreateTime())) return false;
    }
    if (!getItemsList()
        .equals(other.getItemsList())) return false;
    if (hasDownloadUrl() != other.hasDownloadUrl()) return false;
    if (hasDownloadUrl()) {
      if (!getDownloadUrl()
          .equals(other.getDownloadUrl())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BILLING_CYCLE_FIELD_NUMBER;
    hash = (53 * hash) + getBillingCycle().hashCode();
    if (hasCreateTime()) {
      hash = (37 * hash) + CREATE_TIME_FIELD_NUMBER;
      hash = (53 * hash) + getCreateTime().hashCode();
    }
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    if (hasDownloadUrl()) {
      hash = (37 * hash) + DOWNLOAD_URL_FIELD_NUMBER;
      hash = (53 * hash) + getDownloadUrl().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code services.billing.entities.v1alpha2.Invoice}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:services.billing.entities.v1alpha2.Invoice)
      com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceProto.internal_static_services_billing_entities_v1alpha2_Invoice_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceProto.internal_static_services_billing_entities_v1alpha2_Invoice_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.class, com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.Builder.class);
    }

    // Construct using com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      billingCycle_ = "";
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
      } else {
        items_ = null;
        itemsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      downloadUrl_ = null;
      if (downloadUrlBuilder_ != null) {
        downloadUrlBuilder_.dispose();
        downloadUrlBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceProto.internal_static_services_billing_entities_v1alpha2_Invoice_descriptor;
    }

    @java.lang.Override
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice getDefaultInstanceForType() {
      return com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.getDefaultInstance();
    }

    @java.lang.Override
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice build() {
      com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice buildPartial() {
      com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice result = new com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice result) {
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
    }

    private void buildPartial0(com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.billingCycle_ = billingCycle_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.createTime_ = createTimeBuilder_ == null
            ? createTime_
            : createTimeBuilder_.build();
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.downloadUrl_ = downloadUrlBuilder_ == null
            ? downloadUrl_
            : downloadUrlBuilder_.build();
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice) {
        return mergeFrom((com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice other) {
      if (other == com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice.getDefaultInstance()) return this;
      if (!other.getBillingCycle().isEmpty()) {
        billingCycle_ = other.billingCycle_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasCreateTime()) {
        mergeCreateTime(other.getCreateTime());
      }
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000004);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (other.hasDownloadUrl()) {
        mergeDownloadUrl(other.getDownloadUrl());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              billingCycle_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              input.readMessage(
                  getCreateTimeFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem m =
                  input.readMessage(
                      com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.parser(),
                      extensionRegistry);
              if (itemsBuilder_ == null) {
                ensureItemsIsMutable();
                items_.add(m);
              } else {
                itemsBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              input.readMessage(
                  getDownloadUrlFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object billingCycle_ = "";
    /**
     * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
     * @return The billingCycle.
     */
    public java.lang.String getBillingCycle() {
      java.lang.Object ref = billingCycle_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        billingCycle_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
     * @return The bytes for billingCycle.
     */
    public com.google.protobuf.ByteString
        getBillingCycleBytes() {
      java.lang.Object ref = billingCycle_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        billingCycle_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
     * @param value The billingCycle to set.
     * @return This builder for chaining.
     */
    public Builder setBillingCycle(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      billingCycle_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
     * @return This builder for chaining.
     */
    public Builder clearBillingCycle() {
      billingCycle_ = getDefaultInstance().getBillingCycle();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string billing_cycle = 1 [json_name = "billingCycle"];</code>
     * @param value The bytes for billingCycle to set.
     * @return This builder for chaining.
     */
    public Builder setBillingCycleBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      billingCycle_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private com.google.protobuf.Timestamp createTime_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createTimeBuilder_;
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     * @return Whether the createTime field is set.
     */
    public boolean hasCreateTime() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     * @return The createTime.
     */
    public com.google.protobuf.Timestamp getCreateTime() {
      if (createTimeBuilder_ == null) {
        return createTime_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      } else {
        return createTimeBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    public Builder setCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        createTime_ = value;
      } else {
        createTimeBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    public Builder setCreateTime(
        com.google.protobuf.Timestamp.Builder builderForValue) {
      if (createTimeBuilder_ == null) {
        createTime_ = builderForValue.build();
      } else {
        createTimeBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    public Builder mergeCreateTime(com.google.protobuf.Timestamp value) {
      if (createTimeBuilder_ == null) {
        if (((bitField0_ & 0x00000002) != 0) &&
          createTime_ != null &&
          createTime_ != com.google.protobuf.Timestamp.getDefaultInstance()) {
          getCreateTimeBuilder().mergeFrom(value);
        } else {
          createTime_ = value;
        }
      } else {
        createTimeBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    public Builder clearCreateTime() {
      bitField0_ = (bitField0_ & ~0x00000002);
      createTime_ = null;
      if (createTimeBuilder_ != null) {
        createTimeBuilder_.dispose();
        createTimeBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    public com.google.protobuf.Timestamp.Builder getCreateTimeBuilder() {
      bitField0_ |= 0x00000002;
      onChanged();
      return getCreateTimeFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreateTimeOrBuilder() {
      if (createTimeBuilder_ != null) {
        return createTimeBuilder_.getMessageOrBuilder();
      } else {
        return createTime_ == null ?
            com.google.protobuf.Timestamp.getDefaultInstance() : createTime_;
      }
    }
    /**
     * <code>.google.protobuf.Timestamp create_time = 2 [json_name = "createTime"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
        getCreateTimeFieldBuilder() {
      if (createTimeBuilder_ == null) {
        createTimeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                getCreateTime(),
                getParentForChildren(),
                isClean());
        createTime_ = null;
      }
      return createTimeBuilder_;
    }

    private java.util.List<com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        items_ = new java.util.ArrayList<com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem>(items_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder> itemsBuilder_;

    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public java.util.List<com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder setItems(
        int index, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder setItems(
        int index, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder addItems(com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder addItems(
        int index, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder addItems(
        com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder addItems(
        int index, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public java.util.List<? extends com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.getDefaultInstance());
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.getDefaultInstance());
    }
    /**
     * <code>repeated .services.billing.entities.v1alpha2.InvoiceItem items = 3 [json_name = "items"];</code>
     */
    public java.util.List<com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItem.Builder, com.tcn.cloud.api.services.billing.entities.v1alpha2.InvoiceItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private com.google.protobuf.StringValue downloadUrl_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> downloadUrlBuilder_;
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     * @return Whether the downloadUrl field is set.
     */
    public boolean hasDownloadUrl() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     * @return The downloadUrl.
     */
    public com.google.protobuf.StringValue getDownloadUrl() {
      if (downloadUrlBuilder_ == null) {
        return downloadUrl_ == null ? com.google.protobuf.StringValue.getDefaultInstance() : downloadUrl_;
      } else {
        return downloadUrlBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    public Builder setDownloadUrl(com.google.protobuf.StringValue value) {
      if (downloadUrlBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        downloadUrl_ = value;
      } else {
        downloadUrlBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    public Builder setDownloadUrl(
        com.google.protobuf.StringValue.Builder builderForValue) {
      if (downloadUrlBuilder_ == null) {
        downloadUrl_ = builderForValue.build();
      } else {
        downloadUrlBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    public Builder mergeDownloadUrl(com.google.protobuf.StringValue value) {
      if (downloadUrlBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0) &&
          downloadUrl_ != null &&
          downloadUrl_ != com.google.protobuf.StringValue.getDefaultInstance()) {
          getDownloadUrlBuilder().mergeFrom(value);
        } else {
          downloadUrl_ = value;
        }
      } else {
        downloadUrlBuilder_.mergeFrom(value);
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    public Builder clearDownloadUrl() {
      bitField0_ = (bitField0_ & ~0x00000008);
      downloadUrl_ = null;
      if (downloadUrlBuilder_ != null) {
        downloadUrlBuilder_.dispose();
        downloadUrlBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    public com.google.protobuf.StringValue.Builder getDownloadUrlBuilder() {
      bitField0_ |= 0x00000008;
      onChanged();
      return getDownloadUrlFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    public com.google.protobuf.StringValueOrBuilder getDownloadUrlOrBuilder() {
      if (downloadUrlBuilder_ != null) {
        return downloadUrlBuilder_.getMessageOrBuilder();
      } else {
        return downloadUrl_ == null ?
            com.google.protobuf.StringValue.getDefaultInstance() : downloadUrl_;
      }
    }
    /**
     * <code>.google.protobuf.StringValue download_url = 4 [json_name = "downloadUrl"];</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder> 
        getDownloadUrlFieldBuilder() {
      if (downloadUrlBuilder_ == null) {
        downloadUrlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.StringValue, com.google.protobuf.StringValue.Builder, com.google.protobuf.StringValueOrBuilder>(
                getDownloadUrl(),
                getParentForChildren(),
                isClean());
        downloadUrl_ = null;
      }
      return downloadUrlBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:services.billing.entities.v1alpha2.Invoice)
  }

  // @@protoc_insertion_point(class_scope:services.billing.entities.v1alpha2.Invoice)
  private static final com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice();
  }

  public static com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Invoice>
      PARSER = new com.google.protobuf.AbstractParser<Invoice>() {
    @java.lang.Override
    public Invoice parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Invoice> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Invoice> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.tcn.cloud.api.services.billing.entities.v1alpha2.Invoice getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

